### ISSUE TITLE
Debug Building on MSVC-2008 is Impossible

### ISSUE THREAD

**Issue by ZoriaRPG** [ZQuestClassic/ZQuestClassic#79]
I still cannot build a debug version in msvc
MSVC crashes whenever I try.
with this:

2>LINK : fatal error LNK1000: Internal error during IncrBuildImage
2>  Version 9.00.21022.08
2>  ExceptionCode            = C0000005
2>  ExceptionFlags           = 00000000
2>  ExceptionAddress         = 4C003FC0
2>  NumberParameters         = 00000002
2>  ExceptionInformation[ 0] = 00000008
2>  ExceptionInformation[ 1] = 4C003FC0
2>CONTEXT:
2>  Eax    = 4C003FC0  Esp    = 003AEE10
2>  Ebx    = 40008184  Ebp    = 003AEE3C
2>  Ecx    = 00DED670  Esi    = 4064510C
2>  Edx    = 003AEE2C  Edi    = 00EFD6C0
2>  Eip    = 4C003FC0  EFlags = 00010246
2>  SegCs  = 00000023  SegDs  = 0000002B
2>  SegSs  = 0000002B  SegEs  = 0000002B
2>  SegFs  = 00000053  SegGs  = 0000002B
2>  Dr0    = 00000000  Dr3    = 00000000
2>  Dr1    = 00000000  Dr6    = 00000000

See
http://timelord.insomnia247.nl/zc/zc_dev/msvc_debug_errors.txt
for the full log of trying to build in debug mode

Using:

Microsoft Visual Studio 2008
Version 9.0.21022.8 RTM
Microsoft .NET Framework
Version 3.5 SP1

Installed Edition: Professional

**Comment by evouga** [comment]
Does turning off incremental linking in the project properties fix the problem?

**Comment by ZoriaRPG** [comment]
I would try that, but the Linker is not an option under the build properties, for some reason. Could you modify the CMake files to add [/INCREMENTAL:NO] to them?

I'm trying to figure out if I can change the Linker options elsewhere in MSVC, but it's such a pile of soup navigating all of the menus and options, that I suspect a CMake config to disable it would be the best option.

**Comment by ZoriaRPG** [comment]
Oh, never mind. The Linker is only visible on a per binary basis, not for the /whole project/. Strange.

**Comment by evouga** [comment]
> Could you modify the CMake files to add [/INCREMENTAL:NO] to them?

I could, but incremental linking is useful to everyone not using a 10-year-old version of MSVC :)

First verify that turning off incremental linking actually fixes the problem, and if so I will see if there's a way to turn it off specifically for 2008.

**Comment by ZoriaRPG** [comment]
I just built it in debug with incremental linking off. It does fix the issue. 

I would think that you could make a flag to disable it, just as with PCH and other options; but I'm no CMake expert. 

Gleeok will need to know about this. :)

**Comment by ZoriaRPG** [comment]
I just checked the binaries. For whatever reason, without 'libzcsound.dll' (from 2.50.2), Zelda Classic crashes after the title screen (the '2.5 Zelda' screen, not the AGN banner). I suspect that there is no check in place to determine if it is there before continuing to run, that gives an error message and cleanly exits. 

Why is the .dll not generated when compiling? For that matter, why are the allegro 4.4. dlls not generated? Do I need to disable PCH to build them?

I'll post a new issue for the dll crash.

**Comment by evouga** [comment]
See the other thread about libzcsound.dll. If your ZC executable is trying to load it, something is very very wrong with your project configuration (or you have stale .exes from previous compiles laying out and you're accidentally running them).

> For that matter, why are the allegro 4.4. dlls not generated?

It is too big and unwieldy to build as part of ZC. Instructions for how to build it are in the README if you need to rebuild Allegro for some reason.

**Comment by evouga** [comment]
Can you check that this issue is now fixed?

**Comment by Gleeok** [comment]
This is why nothing ever works right most of the time I try to compile a library that uses a CMAKE only build system. It's not CMAKE per se, but everything else that's broken. Go figure.

I still don't mind maintaining legacy VS 2008 project files if need be. I still use 2008 99% of the time and only switch to VS 2015 for release builds to generate more efficient vectorized code.

**Comment by ZoriaRPG** [comment]
It only occurred with the debug build, when not using the incremental linker. My release builds do not seem to have this problem.

**Comment by evouga** [comment]
Did my change to turn off incremental linknig work for you, though?

**Comment by ZoriaRPG** [comment]
Hmm? The last time I built debug without manually deselecting incremental Linking, it had a similar issue. I will re-check it as soon as you complete the internal changes.

**Comment by ZoriaRPG** [comment]
Seems to work now.
